apiVersion: v1
kind: Service
metadata:
  name: {{ include "ftok.fullname" . }}
  labels:
    {{- include "ftok.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5000
      protocol: TCP
      name: flask
  selector:
    {{- include "ftok.selectorLabels" . | nindent 4 }}
